spring:
  main:
    allow-bean-definition-overriding: true
  rabbitmq:
    host: ${RABBIT_MQ_HOST:10.2.95.149}
    port: ${RABBIT_MQ_PORT:5672}
    username: ${RABBIT_MQ_USERNAME:guest}
    password: ${RABBIT_MQ_PASSWORD:guest}
  redis:
    host: ${REDIS_HOST:10.2.95.149}
    port: 6379
    password:
  cache:
    redis:
      time-to-live: 1d
      use-key-prefix: true
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:47.94.39.182}:3306/fast-auth?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF8&autoReconnect=true&useSSL=false
    username: root
    password: Wdadmin@2020
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_HOST:10.2.95.149}:9999
feign:
  hystrix:
    enabled: true
hystrix:
  threadpool:
    default:
      coreSize: 1000 #并发执行的最大线程数，默认10
      maxQueueSize: 1000 #BlockingQueue的最大队列数
      queueSizeRejectionThreshold: 500 #即使maxQueueSize没有达到，达到queueSizeRejectionThreshold该值后，请求也会被拒绝
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
#admin监控
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"    #监控所有端点，其中health和status是必须监控的
        exclude: configprops    #排除对配置信息的监控，每次浏览这个节点的时候，
          #数据库的链接就一直释放不掉，最后导致超时，因为配置信息的监控也不重要，
          #就不再监控这个节点，以下为可监控的endpoint。可以根据需要有选择的进行监控。
          #- health,status,env,metrics,dump,jolokia,info,
        #configprops,trace,logfile,refresh,flyway,
        #liquibase,heapdump,loggers,auditevents,hystrix.stream,activiti
  metrics:
    web:
      server:
        auto-time-requests: false
logging:
  level:
    cn.fast.admin: debug
    #    org.springframework.security: debug
    org.springframework.web: debug